name: Continuous Integration
on: pull_request
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with: 
                ref: ${{ github.event.pull_request.head.sha }}
            - name: Build
              run: |
                docker build -t slack/hack-json-schema .
            - name: Install
              run: |
                docker run -v `pwd`:/app slack/hack-json-schema composer install 
            - name: Typecheck
              run: | 
                docker run -v `pwd`:/app slack/hack-json-schema hh_client
            - name: Test
              run: |
                docker run -v `pwd`:/app slack/hack-json-schema ./vendor/bin/hacktest tests